/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Animal = IDL.Variant({
  'poultry' : IDL.Null,
  'cats' : IDL.Null,
  'dogs' : IDL.Null,
  'pigs' : IDL.Null,
  'sheep' : IDL.Null,
  'goats' : IDL.Null,
  'cattle' : IDL.Null,
  'horses' : IDL.Null,
  'rabbits' : IDL.Null,
});
export const DiseaseView = IDL.Record({
  'name' : IDL.Text,
  'treatment' : IDL.Text,
  'affectedAnimals' : IDL.Vec(Animal),
  'symptoms' : IDL.Vec(IDL.Text),
  'severity' : IDL.Variant({
    'mild' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  }),
  'causes' : IDL.Text,
  'prevention' : IDL.Text,
});
export const DrugView = IDL.Record({
  'dosage' : IDL.Text,
  'quality' : IDL.Vec(IDL.Text),
  'indications' : IDL.Vec(IDL.Text),
  'treats' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'contraindications' : IDL.Vec(IDL.Text),
  'sideEffects' : IDL.Vec(IDL.Text),
  'drugClass' : IDL.Text,
  'route' : IDL.Variant({
    'injection' : IDL.Null,
    'oral' : IDL.Null,
    'topical' : IDL.Null,
  }),
});
export const ManagementTipView = IDL.Record({
  'tips' : IDL.Record({
    'vaccination' : IDL.Text,
    'feeding' : IDL.Text,
    'healthMonitoring' : IDL.Text,
    'hygiene' : IDL.Text,
    'housing' : IDL.Text,
  }),
  'animalType' : Animal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDisease' : IDL.Func([DiseaseView], [], []),
  'createDrug' : IDL.Func([DrugView], [], []),
  'createManagementTip' : IDL.Func([ManagementTipView], [], []),
  'deleteDisease' : IDL.Func([IDL.Text], [], []),
  'deleteDrug' : IDL.Func([IDL.Text], [], []),
  'deleteManagementTip' : IDL.Func([Animal], [], []),
  'getAllDiseases' : IDL.Func([], [IDL.Vec(DiseaseView)], ['query']),
  'getAllDrugs' : IDL.Func([], [IDL.Vec(DrugView)], ['query']),
  'getAllManagementTips' : IDL.Func(
      [],
      [IDL.Vec(ManagementTipView)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisease' : IDL.Func([IDL.Text], [IDL.Opt(DiseaseView)], ['query']),
  'getDrug' : IDL.Func([IDL.Text], [IDL.Opt(DrugView)], ['query']),
  'getManagementTip' : IDL.Func(
      [Animal],
      [IDL.Opt(ManagementTipView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchDiseasesByAnimal' : IDL.Func(
      [Animal],
      [IDL.Vec(DiseaseView)],
      ['query'],
    ),
  'searchDrugsByIndication' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DrugView)],
      ['query'],
    ),
  'updateDisease' : IDL.Func([IDL.Text, DiseaseView], [], []),
  'updateDrug' : IDL.Func([IDL.Text, DrugView], [], []),
  'updateManagementTip' : IDL.Func([ManagementTipView], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Animal = IDL.Variant({
    'poultry' : IDL.Null,
    'cats' : IDL.Null,
    'dogs' : IDL.Null,
    'pigs' : IDL.Null,
    'sheep' : IDL.Null,
    'goats' : IDL.Null,
    'cattle' : IDL.Null,
    'horses' : IDL.Null,
    'rabbits' : IDL.Null,
  });
  const DiseaseView = IDL.Record({
    'name' : IDL.Text,
    'treatment' : IDL.Text,
    'affectedAnimals' : IDL.Vec(Animal),
    'symptoms' : IDL.Vec(IDL.Text),
    'severity' : IDL.Variant({
      'mild' : IDL.Null,
      'severe' : IDL.Null,
      'moderate' : IDL.Null,
    }),
    'causes' : IDL.Text,
    'prevention' : IDL.Text,
  });
  const DrugView = IDL.Record({
    'dosage' : IDL.Text,
    'quality' : IDL.Vec(IDL.Text),
    'indications' : IDL.Vec(IDL.Text),
    'treats' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'contraindications' : IDL.Vec(IDL.Text),
    'sideEffects' : IDL.Vec(IDL.Text),
    'drugClass' : IDL.Text,
    'route' : IDL.Variant({
      'injection' : IDL.Null,
      'oral' : IDL.Null,
      'topical' : IDL.Null,
    }),
  });
  const ManagementTipView = IDL.Record({
    'tips' : IDL.Record({
      'vaccination' : IDL.Text,
      'feeding' : IDL.Text,
      'healthMonitoring' : IDL.Text,
      'hygiene' : IDL.Text,
      'housing' : IDL.Text,
    }),
    'animalType' : Animal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDisease' : IDL.Func([DiseaseView], [], []),
    'createDrug' : IDL.Func([DrugView], [], []),
    'createManagementTip' : IDL.Func([ManagementTipView], [], []),
    'deleteDisease' : IDL.Func([IDL.Text], [], []),
    'deleteDrug' : IDL.Func([IDL.Text], [], []),
    'deleteManagementTip' : IDL.Func([Animal], [], []),
    'getAllDiseases' : IDL.Func([], [IDL.Vec(DiseaseView)], ['query']),
    'getAllDrugs' : IDL.Func([], [IDL.Vec(DrugView)], ['query']),
    'getAllManagementTips' : IDL.Func(
        [],
        [IDL.Vec(ManagementTipView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisease' : IDL.Func([IDL.Text], [IDL.Opt(DiseaseView)], ['query']),
    'getDrug' : IDL.Func([IDL.Text], [IDL.Opt(DrugView)], ['query']),
    'getManagementTip' : IDL.Func(
        [Animal],
        [IDL.Opt(ManagementTipView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchDiseasesByAnimal' : IDL.Func(
        [Animal],
        [IDL.Vec(DiseaseView)],
        ['query'],
      ),
    'searchDrugsByIndication' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DrugView)],
        ['query'],
      ),
    'updateDisease' : IDL.Func([IDL.Text, DiseaseView], [], []),
    'updateDrug' : IDL.Func([IDL.Text, DrugView], [], []),
    'updateManagementTip' : IDL.Func([ManagementTipView], [], []),
  });
};

export const init = ({ IDL }) => { return []; };