/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Animal = { 'poultry' : null } |
  { 'cats' : null } |
  { 'dogs' : null } |
  { 'pigs' : null } |
  { 'sheep' : null } |
  { 'goats' : null } |
  { 'cattle' : null } |
  { 'horses' : null } |
  { 'rabbits' : null };
export interface DiseaseView {
  'name' : string,
  'treatment' : string,
  'affectedAnimals' : Array<Animal>,
  'symptoms' : Array<string>,
  'severity' : { 'mild' : null } |
    { 'severe' : null } |
    { 'moderate' : null },
  'causes' : string,
  'prevention' : string,
}
export interface DrugView {
  'dosage' : string,
  'quality' : Array<string>,
  'indications' : Array<string>,
  'treats' : Array<string>,
  'name' : string,
  'contraindications' : Array<string>,
  'sideEffects' : Array<string>,
  'drugClass' : string,
  'route' : { 'injection' : null } |
    { 'oral' : null } |
    { 'topical' : null },
}
export interface ManagementTipView {
  'tips' : {
    'vaccination' : string,
    'feeding' : string,
    'healthMonitoring' : string,
    'hygiene' : string,
    'housing' : string,
  },
  'animalType' : Animal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDisease' : ActorMethod<[DiseaseView], undefined>,
  'createDrug' : ActorMethod<[DrugView], undefined>,
  'createManagementTip' : ActorMethod<[ManagementTipView], undefined>,
  'deleteDisease' : ActorMethod<[string], undefined>,
  'deleteDrug' : ActorMethod<[string], undefined>,
  'deleteManagementTip' : ActorMethod<[Animal], undefined>,
  'getAllDiseases' : ActorMethod<[], Array<DiseaseView>>,
  'getAllDrugs' : ActorMethod<[], Array<DrugView>>,
  'getAllManagementTips' : ActorMethod<[], Array<ManagementTipView>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisease' : ActorMethod<[string], [] | [DiseaseView]>,
  'getDrug' : ActorMethod<[string], [] | [DrugView]>,
  'getManagementTip' : ActorMethod<[Animal], [] | [ManagementTipView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchDiseasesByAnimal' : ActorMethod<[Animal], Array<DiseaseView>>,
  'searchDrugsByIndication' : ActorMethod<[string], Array<DrugView>>,
  'updateDisease' : ActorMethod<[string, DiseaseView], undefined>,
  'updateDrug' : ActorMethod<[string, DrugView], undefined>,
  'updateManagementTip' : ActorMethod<[ManagementTipView], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];