/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ManagementTipView {
    tips: {
        vaccination: string;
        feeding: string;
        healthMonitoring: string;
        hygiene: string;
        housing: string;
    };
    animalType: Animal;
}
export interface DrugView {
    dosage: string;
    quality: Array<string>;
    indications: Array<string>;
    treats: Array<string>;
    name: string;
    contraindications: Array<string>;
    sideEffects: Array<string>;
    drugClass: string;
    route: Variant_injection_oral_topical;
}
export interface DiseaseView {
    name: string;
    treatment: string;
    affectedAnimals: Array<Animal>;
    symptoms: Array<string>;
    severity: Variant_mild_severe_moderate;
    causes: string;
    prevention: string;
}
export enum Animal {
    poultry = "poultry",
    cats = "cats",
    dogs = "dogs",
    pigs = "pigs",
    sheep = "sheep",
    goats = "goats",
    cattle = "cattle",
    horses = "horses",
    rabbits = "rabbits"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_injection_oral_topical {
    injection = "injection",
    oral = "oral",
    topical = "topical"
}
export enum Variant_mild_severe_moderate {
    mild = "mild",
    severe = "severe",
    moderate = "moderate"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDisease(disease: DiseaseView): Promise<void>;
    createDrug(drug: DrugView): Promise<void>;
    createManagementTip(tip: ManagementTipView): Promise<void>;
    deleteDisease(name: string): Promise<void>;
    deleteDrug(name: string): Promise<void>;
    deleteManagementTip(animal: Animal): Promise<void>;
    getAllDiseases(): Promise<Array<DiseaseView>>;
    getAllDrugs(): Promise<Array<DrugView>>;
    getAllManagementTips(): Promise<Array<ManagementTipView>>;
    getCallerUserRole(): Promise<UserRole>;
    getDisease(name: string): Promise<DiseaseView | null>;
    getDrug(name: string): Promise<DrugView | null>;
    getManagementTip(animal: Animal): Promise<ManagementTipView | null>;
    isCallerAdmin(): Promise<boolean>;
    searchDiseasesByAnimal(animal: Animal): Promise<Array<DiseaseView>>;
    searchDrugsByIndication(indication: string): Promise<Array<DrugView>>;
    updateDisease(name: string, newDisease: DiseaseView): Promise<void>;
    updateDrug(name: string, newDrug: DrugView): Promise<void>;
    updateManagementTip(tip: ManagementTipView): Promise<void>;
}
import type { Animal as _Animal, DiseaseView as _DiseaseView, DrugView as _DrugView, ManagementTipView as _ManagementTipView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDisease(arg0: DiseaseView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDisease(to_candid_DiseaseView_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDisease(to_candid_DiseaseView_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDrug(arg0: DrugView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDrug(to_candid_DrugView_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDrug(to_candid_DrugView_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createManagementTip(arg0: ManagementTipView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createManagementTip(to_candid_ManagementTipView_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createManagementTip(to_candid_ManagementTipView_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteDisease(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDisease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDisease(arg0);
            return result;
        }
    }
    async deleteDrug(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDrug(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDrug(arg0);
            return result;
        }
    }
    async deleteManagementTip(arg0: Animal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManagementTip(to_candid_Animal_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManagementTip(to_candid_Animal_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllDiseases(): Promise<Array<DiseaseView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiseases();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiseases();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDrugs(): Promise<Array<DrugView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrugs();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrugs();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllManagementTips(): Promise<Array<ManagementTipView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllManagementTips();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllManagementTips();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDisease(arg0: string): Promise<DiseaseView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisease(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisease(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrug(arg0: string): Promise<DrugView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrug(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrug(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManagementTip(arg0: Animal): Promise<ManagementTipView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagementTip(to_candid_Animal_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagementTip(to_candid_Animal_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async searchDiseasesByAnimal(arg0: Animal): Promise<Array<DiseaseView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDiseasesByAnimal(to_candid_Animal_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDiseasesByAnimal(to_candid_Animal_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchDrugsByIndication(arg0: string): Promise<Array<DrugView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDrugsByIndication(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDrugsByIndication(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDisease(arg0: string, arg1: DiseaseView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisease(arg0, to_candid_DiseaseView_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisease(arg0, to_candid_DiseaseView_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDrug(arg0: string, arg1: DrugView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDrug(arg0, to_candid_DrugView_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDrug(arg0, to_candid_DrugView_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateManagementTip(arg0: ManagementTipView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateManagementTip(to_candid_ManagementTipView_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateManagementTip(to_candid_ManagementTipView_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Animal_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Animal): Animal {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DiseaseView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiseaseView): DiseaseView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DrugView_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrugView): DrugView {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ManagementTipView_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagementTipView): ManagementTipView {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiseaseView]): DiseaseView | null {
    return value.length === 0 ? null : from_candid_DiseaseView_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DrugView]): DrugView | null {
    return value.length === 0 ? null : from_candid_DrugView_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ManagementTipView]): ManagementTipView | null {
    return value.length === 0 ? null : from_candid_ManagementTipView_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    treatment: string;
    affectedAnimals: Array<_Animal>;
    symptoms: Array<string>;
    severity: {
        mild: null;
    } | {
        severe: null;
    } | {
        moderate: null;
    };
    causes: string;
    prevention: string;
}): {
    name: string;
    treatment: string;
    affectedAnimals: Array<Animal>;
    symptoms: Array<string>;
    severity: Variant_mild_severe_moderate;
    causes: string;
    prevention: string;
} {
    return {
        name: value.name,
        treatment: value.treatment,
        affectedAnimals: from_candid_vec_n17(_uploadFile, _downloadFile, value.affectedAnimals),
        symptoms: value.symptoms,
        severity: from_candid_variant_n20(_uploadFile, _downloadFile, value.severity),
        causes: value.causes,
        prevention: value.prevention
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dosage: string;
    quality: Array<string>;
    indications: Array<string>;
    treats: Array<string>;
    name: string;
    contraindications: Array<string>;
    sideEffects: Array<string>;
    drugClass: string;
    route: {
        injection: null;
    } | {
        oral: null;
    } | {
        topical: null;
    };
}): {
    dosage: string;
    quality: Array<string>;
    indications: Array<string>;
    treats: Array<string>;
    name: string;
    contraindications: Array<string>;
    sideEffects: Array<string>;
    drugClass: string;
    route: Variant_injection_oral_topical;
} {
    return {
        dosage: value.dosage,
        quality: value.quality,
        indications: value.indications,
        treats: value.treats,
        name: value.name,
        contraindications: value.contraindications,
        sideEffects: value.sideEffects,
        drugClass: value.drugClass,
        route: from_candid_variant_n24(_uploadFile, _downloadFile, value.route)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tips: {
        vaccination: string;
        feeding: string;
        healthMonitoring: string;
        hygiene: string;
        housing: string;
    };
    animalType: _Animal;
}): {
    tips: {
        vaccination: string;
        feeding: string;
        healthMonitoring: string;
        hygiene: string;
        housing: string;
    };
    animalType: Animal;
} {
    return {
        tips: value.tips,
        animalType: from_candid_Animal_n18(_uploadFile, _downloadFile, value.animalType)
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    poultry: null;
} | {
    cats: null;
} | {
    dogs: null;
} | {
    pigs: null;
} | {
    sheep: null;
} | {
    goats: null;
} | {
    cattle: null;
} | {
    horses: null;
} | {
    rabbits: null;
}): Animal {
    return "poultry" in value ? Animal.poultry : "cats" in value ? Animal.cats : "dogs" in value ? Animal.dogs : "pigs" in value ? Animal.pigs : "sheep" in value ? Animal.sheep : "goats" in value ? Animal.goats : "cattle" in value ? Animal.cattle : "horses" in value ? Animal.horses : "rabbits" in value ? Animal.rabbits : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
}): Variant_mild_severe_moderate {
    return "mild" in value ? Variant_mild_severe_moderate.mild : "severe" in value ? Variant_mild_severe_moderate.severe : "moderate" in value ? Variant_mild_severe_moderate.moderate : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    injection: null;
} | {
    oral: null;
} | {
    topical: null;
}): Variant_injection_oral_topical {
    return "injection" in value ? Variant_injection_oral_topical.injection : "oral" in value ? Variant_injection_oral_topical.oral : "topical" in value ? Variant_injection_oral_topical.topical : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiseaseView>): Array<DiseaseView> {
    return value.map((x)=>from_candid_DiseaseView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Animal>): Array<Animal> {
    return value.map((x)=>from_candid_Animal_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DrugView>): Array<DrugView> {
    return value.map((x)=>from_candid_DrugView_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ManagementTipView>): Array<ManagementTipView> {
    return value.map((x)=>from_candid_ManagementTipView_n26(_uploadFile, _downloadFile, x));
}
function to_candid_Animal_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Animal): _Animal {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DiseaseView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiseaseView): _DiseaseView {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DrugView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrugView): _DrugView {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ManagementTipView_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagementTipView): _ManagementTipView {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dosage: string;
    quality: Array<string>;
    indications: Array<string>;
    treats: Array<string>;
    name: string;
    contraindications: Array<string>;
    sideEffects: Array<string>;
    drugClass: string;
    route: Variant_injection_oral_topical;
}): {
    dosage: string;
    quality: Array<string>;
    indications: Array<string>;
    treats: Array<string>;
    name: string;
    contraindications: Array<string>;
    sideEffects: Array<string>;
    drugClass: string;
    route: {
        injection: null;
    } | {
        oral: null;
    } | {
        topical: null;
    };
} {
    return {
        dosage: value.dosage,
        quality: value.quality,
        indications: value.indications,
        treats: value.treats,
        name: value.name,
        contraindications: value.contraindications,
        sideEffects: value.sideEffects,
        drugClass: value.drugClass,
        route: to_candid_variant_n11(_uploadFile, _downloadFile, value.route)
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tips: {
        vaccination: string;
        feeding: string;
        healthMonitoring: string;
        hygiene: string;
        housing: string;
    };
    animalType: Animal;
}): {
    tips: {
        vaccination: string;
        feeding: string;
        healthMonitoring: string;
        hygiene: string;
        housing: string;
    };
    animalType: _Animal;
} {
    return {
        tips: value.tips,
        animalType: to_candid_Animal_n6(_uploadFile, _downloadFile, value.animalType)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    treatment: string;
    affectedAnimals: Array<Animal>;
    symptoms: Array<string>;
    severity: Variant_mild_severe_moderate;
    causes: string;
    prevention: string;
}): {
    name: string;
    treatment: string;
    affectedAnimals: Array<_Animal>;
    symptoms: Array<string>;
    severity: {
        mild: null;
    } | {
        severe: null;
    } | {
        moderate: null;
    };
    causes: string;
    prevention: string;
} {
    return {
        name: value.name,
        treatment: value.treatment,
        affectedAnimals: to_candid_vec_n5(_uploadFile, _downloadFile, value.affectedAnimals),
        symptoms: value.symptoms,
        severity: to_candid_variant_n8(_uploadFile, _downloadFile, value.severity),
        causes: value.causes,
        prevention: value.prevention
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_injection_oral_topical): {
    injection: null;
} | {
    oral: null;
} | {
    topical: null;
} {
    return value == Variant_injection_oral_topical.injection ? {
        injection: null
    } : value == Variant_injection_oral_topical.oral ? {
        oral: null
    } : value == Variant_injection_oral_topical.topical ? {
        topical: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Animal): {
    poultry: null;
} | {
    cats: null;
} | {
    dogs: null;
} | {
    pigs: null;
} | {
    sheep: null;
} | {
    goats: null;
} | {
    cattle: null;
} | {
    horses: null;
} | {
    rabbits: null;
} {
    return value == Animal.poultry ? {
        poultry: null
    } : value == Animal.cats ? {
        cats: null
    } : value == Animal.dogs ? {
        dogs: null
    } : value == Animal.pigs ? {
        pigs: null
    } : value == Animal.sheep ? {
        sheep: null
    } : value == Animal.goats ? {
        goats: null
    } : value == Animal.cattle ? {
        cattle: null
    } : value == Animal.horses ? {
        horses: null
    } : value == Animal.rabbits ? {
        rabbits: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_mild_severe_moderate): {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
} {
    return value == Variant_mild_severe_moderate.mild ? {
        mild: null
    } : value == Variant_mild_severe_moderate.severe ? {
        severe: null
    } : value == Variant_mild_severe_moderate.moderate ? {
        moderate: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Animal>): Array<_Animal> {
    return value.map((x)=>to_candid_Animal_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
